export default function robots() {
  return {
    rules: {
      userAgent: '*',
      allow: [
        '/',
        '/shop',
        '/shop-category',
        '/category',
        '/product/',
        '/about',
        '/terms',
        '/returns',
        '/history',
        '/search',
      ],
      disallow: [
        '/api/',
        '/login',
        '/register',
        '/profile',
        '/cart',
        '/checkout',
        '/order',
        '/wishlist',
        '/compare',
        '/coupon',
        '/forgot',
        '/email-verify',
        '/forget-password',
        '/_next/',
        '/_next/static/',
        '/_next/static/chunks/',
        '/_next/static/css/',
        '/_next/static/media/',
        '/_next/image',
        '/admin/',
        '/dashboard/',
        '*.json',
        '*.js',
        '*.css',
        '*.map',
        '*.txt',
        '/webhook/',
        '/favicon.ico',
        '/manifest.json',
        '/sw.js',
        '/workbox-*',
      ],
    },
    sitemap: 'https://www.eastwestoffroad.com/sitemap.xml',
  };
}
