export default function robots() {
  return {
    rules: [
      {
        userAgent: 'OAI-SearchBot',
        allow: '/',
      },
      {
        userAgent: '*',
        allow: [
          '/',
          '/shop',
          '/shop-category',
          '/category',
          '/product/',
          '/about',
          '/terms',
          '/returns',
          '/history',
          '/search',
        ],
        disallow: [
          '/api/',
          '/login',
          '/register',
          '/profile',
          '/cart',
          '/checkout',
          '/order',
          '/wishlist',
          '/compare',
          '/coupon',
          '/forgot',
          '/email-verify',
          '/forget-password',
          '/admin/',
          '/dashboard/',
          '*.json',
          '*.js',
          '*.css',
          '*.map',
          '*.txt',
          '/webhook/',
          '/favicon.ico',
          '/manifest.json',
          '/sw.js',
          '/workbox-*',
        ],
      },
    ],
    sitemap: 'https://www.eastwestoffroad.com/sitemap.xml',
  };
}
